---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=${bosh-version}
  sha1: ${bosh-sha1}
- name: bosh-aws-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=${bosh-aws_cpi_version}
  sha1: ${bosh-aws_cpi_sha1}

resource_pools:
- name: vms
  network: private
  stemcell:
    #url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-centos-7-go_agent?v=${centos_stemcell_version}
    #sha1: ${centos_stemcell_sha1}
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3012
    sha1: 3380b55948abe4c437dee97f67d2d8df4eec3fc1

  cloud_properties:
    instance_type: ${bosh-director_vm_size}
    ephemeral_disk: {size: 40_000, type: gp2}
    root_disk: {size: 40_000, type: gp2}
    availability_zone: ${bosh-az}

disk_pools:
- name: disks
  disk_size: 40_000
  cloud_properties: {type: gp2, size: 40_000}

networks:
- name: private
  type: manual
  subnets:
  - range: ${network}.1.0/24
    gateway: ${network}.1.1
    dns: [${network}.0.2]
    cloud_properties: {subnet: ${bosh-subnet}}

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: redis, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: aws_cpi, release: bosh-aws-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [${network}.1.6]
    default: [dns, gateway]

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nat5pa55

    redis:
      listen_address: 127.0.0.1
      address: 127.0.0.1
      password: redi5pa55

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgr35pa55
      database: bosh
      adapter: postgres

    registry:
      address: ${network}.1.6
      host: ${network}.1.6
      db: *db
      http: {user: admin, password: admin, port: 25777}
      username: admin
      password: admin
      port: 25777

    blobstore:
      address: ${network}.1.6
      port: 25250
      provider: dav
      director: {user: director, password: directorpa55}
      agent: {user: agent, password: agentpa55}

    director:
      address: 127.0.0.1
      name: herr-director
      db: *db
      cpi_job: aws_cpi
      max_threads: 10
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: adminpa55}
          - {name: hm, password: hmpa55}

    hm:
      director_account: {user: hm, password: hmpa55}
      resurrector_enabled: true

    aws: &aws
      access_key_id: ${aws-access_key}
      secret_access_key: ${aws-secret_key}
      default_key_name: ${aws-key_name}
      default_security_groups: [${aws-security-group}]
      region: ${aws-region}

    agent: {mbus: "nats://nats:nat5pa55@${network}.1.6:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: aws_cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    host: ${network}.1.6
    port: 22
    user: vcap
    private_key: ~/.ssh/bosh.pem

  mbus: "https://mbus:mbu5pa55@${network}.1.6:6868"

  properties:
    aws: *aws
    agent: {mbus: "https://mbus:mbu5pa55@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
